import os
from dotenv import load_dotenv

load_dotenv()

# GLOBAL INFORMATION VARIABLES ICE API
ICE_HOST=os.getenv("ICE_HOST")
ICE_AUTH=os.getenv("ICE_AUTH")

ICE_USERNAME=os.getenv("ICE_USERNAME")
ICE_PASSWORD=os.getenv("ICE_PASSWORD")

ICE_URL_SEARCH_TRADES=os.getenv("ICE_URL_SEARCH_TRADES")
ICE_URL_GET_TRADES=os.getenv("ICE_URL_GET_TRADES")
ICE_URL_CALC_RES=os.getenv("ICE_URL_CALC_RES")
ICE_URL_BIL_IM_CALC=os.getenv("ICE_URL_BIL_IM_CALC")
ICE_URL_TRADE_ADD=os.getenv("ICE_URL_TRADE_ADD")

API_LOG_REQUEST_FILE_PATH=os.getenv("API_LOG_REQUEST_FILE_PATH")
FILE_ID_CALCULATION_PATH=os.getenv("FILE_ID_CALCULATION_PATH")
PRICING_LOG_FILE_PATH=os.getenv("PRICING_LOG_FILE_PATH")
SAVED_REQUESTS_DIRECTORY_PATH=os.getenv("SAVED_REQUESTS_DIRECTORY_PATH")

# instruments concurrencies
CCYS_ORDER=['EUR', 'USD', 'CHF', 'CAD', 'JPY', 'GBP', 'SEK', 'NOK']